name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t tonyaji19/cicdjenkins:${{ github.sha }} .

      - name: Push Docker Image to Docker Hub
        run: docker push tonyaji19/cicdjenkins:${{ github.sha }}

      - name: Trigger Jenkins Job
        run: curl -X POST http://103.160.62.183:8080/job/cicdtonyaji/build \
             --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}
