name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t tonyaji19/cicdjenkins:${{ github.sha }} .

      - name: Push Docker Image to Docker Hub
        run: docker push tonyaji19/cicdjenkins:${{ github.sha }}

      - name: Get Jenkins Crumb and Trigger Jenkins Job
        run: |
          # Mendapatkan Jenkins Crumb dengan cara yang benar
          CRUMB=$(curl -s -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            "http://103.160.62.183:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,':',//crumb)")

          echo "Crumb: $CRUMB"

          # Memeriksa apakah CRUMB berhasil didapatkan
          if [ -z "$CRUMB" ]; then
            echo "Failed to get Jenkins Crumb"
            exit 1
          fi
          
          # Trigger Jenkins Job dengan crumb yang valid
          curl -X POST "http://103.160.62.183:8080/job/cicdtonyaji/build" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            -H "$CRUMB"

